package lc.fungee.Ingredicheck.onboarding.model

enum class OnboardingStep {
    GET_STARTED,
    SIGN_IN_INITIAL,
    SIGN_IN_SOCIAL_LOGIN,
    SIGN_IN_INVITE_CODE,
    SIGN_IN_ENTER_INVITE_CODE,
    SIGN_IN_WHO_IS_THIS_FOR,
    ADD_FAMILY_WELCOME,
    ADD_FAMILY_NAME,
    ADD_FAMILY_AVATAR_PICKER,
    ADD_FAMILY_AVATAR_GENERATING
}
